root = ""
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./main frontend"
  cmd = "go build ./cmd/hotrod/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "services/frontend/web_assets/"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["services/frontend"]
  include_ext = ["go", "tpl", "tmpl", "html", "tsx", "ts"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["make build-frontend-app"]
  rerun = true
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
