#!/usr/bin/env bash

set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: provision <sandbox-id> <resource-name>"
  exit 1
fi

INPUT_DIR=/signadot/provision/input
OUTPUT_DIR=/signadot/provision/output

# Get values passed to us by Signadot Operator.
# These tell us which resource name in which Sandbox we should provision.
SANDBOX_ID=$1
RESOURCE_NAME=$2

echo "sandbox id: ${SANDBOX_ID}"
echo "resource name: ${RESOURCE_NAME}"

# Get values passed to us as "params" in the Sandbox's "resources" section.
DBNAME=$(cat ${INPUT_DIR}/dbname)
echo "dbname: ${DBNAME}"

# Deploy a temporary DB for this Sandbox in the 'signadot' namespace.
RELEASE_NAME="hotrod-${RESOURCE_NAME}-${SANDBOX_ID}"
echo "Installing Helm release: ${RELEASE_NAME}"
helm -n signadot install "${RELEASE_NAME}" bitnami/mariadb \
  --set primary.persistence.enabled=false \
  --set serviceAccount.create=false \
  --set auth.database="${DBNAME}"

# Get the generated password, based on instructions from the Helm chart.
MYSQL_ROOT_PASSWORD=$(kubectl -n signadot get secret "${RELEASE_NAME}-mariadb" -o jsonpath="{.data.mariadb-root-password}" | base64 -d)

# Wait until the DB is available according to the Helm chart's readinessProbe.
POD="${RELEASE_NAME}-mariadb-0"
echo "Waiting for Pod signadot/${POD} to be Ready..."
kubectl -n signadot wait --for=condition=Ready --timeout=5m "pod/${POD}"

# Tell the fork(s) how to connect.
DBHOST="${RELEASE_NAME}-mariadb.signadot.svc"
echo -n "${DBHOST}" > ${OUTPUT_DIR}/host
echo -n 3306 > ${OUTPUT_DIR}/port
echo -n "${MYSQL_ROOT_PASSWORD}" > ${OUTPUT_DIR}/root_password
