apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  ports:
  - name: "http-otlp"
    port: 4318
    protocol: UDP
  - name: "http-frontend"
    port: 16686
    protocol: TCP
  selector:
    app: jaeger
