// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: services/route/route.proto

package route

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRouteRequest) Reset() {
	*x = FindRouteRequest{}
	mi := &file_services_route_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRouteRequest) ProtoMessage() {}

func (x *FindRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_route_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRouteRequest.ProtoReflect.Descriptor instead.
func (*FindRouteRequest) Descriptor() ([]byte, []int) {
	return file_services_route_route_proto_rawDescGZIP(), []int{0}
}

func (x *FindRouteRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *FindRouteRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type FindRouteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EtaSeconds     int32                  `protobuf:"varint,1,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	DistanceMeters int32                  `protobuf:"varint,2,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindRouteResponse) Reset() {
	*x = FindRouteResponse{}
	mi := &file_services_route_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRouteResponse) ProtoMessage() {}

func (x *FindRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_route_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRouteResponse.ProtoReflect.Descriptor instead.
func (*FindRouteResponse) Descriptor() ([]byte, []int) {
	return file_services_route_route_proto_rawDescGZIP(), []int{1}
}

func (x *FindRouteResponse) GetEtaSeconds() int32 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

func (x *FindRouteResponse) GetDistanceMeters() int32 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

var File_services_route_route_proto protoreflect.FileDescriptor

const file_services_route_route_proto_rawDesc = "" +
	"\n" +
	"\x1aservices/route/route.proto\x12\x05route\"6\n" +
	"\x10FindRouteRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"]\n" +
	"\x11FindRouteResponse\x12\x1f\n" +
	"\veta_seconds\x18\x01 \x01(\x05R\n" +
	"etaSeconds\x12'\n" +
	"\x0fdistance_meters\x18\x02 \x01(\x05R\x0edistanceMeters2O\n" +
	"\rRoutesService\x12>\n" +
	"\tFindRoute\x12\x17.route.FindRouteRequest\x1a\x18.route.FindRouteResponseB+Z)github.com/signadot/hotrod/services/routeb\x06proto3"

var (
	file_services_route_route_proto_rawDescOnce sync.Once
	file_services_route_route_proto_rawDescData []byte
)

func file_services_route_route_proto_rawDescGZIP() []byte {
	file_services_route_route_proto_rawDescOnce.Do(func() {
		file_services_route_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_route_route_proto_rawDesc), len(file_services_route_route_proto_rawDesc)))
	})
	return file_services_route_route_proto_rawDescData
}

var file_services_route_route_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_route_route_proto_goTypes = []any{
	(*FindRouteRequest)(nil),  // 0: route.FindRouteRequest
	(*FindRouteResponse)(nil), // 1: route.FindRouteResponse
}
var file_services_route_route_proto_depIdxs = []int32{
	0, // 0: route.RoutesService.FindRoute:input_type -> route.FindRouteRequest
	1, // 1: route.RoutesService.FindRoute:output_type -> route.FindRouteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_route_route_proto_init() }
func file_services_route_route_proto_init() {
	if File_services_route_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_route_route_proto_rawDesc), len(file_services_route_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_route_route_proto_goTypes,
		DependencyIndexes: file_services_route_route_proto_depIdxs,
		MessageInfos:      file_services_route_route_proto_msgTypes,
	}.Build()
	File_services_route_route_proto = out.File
	file_services_route_route_proto_goTypes = nil
	file_services_route_route_proto_depIdxs = nil
}
