// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: services/route/route.proto

package route

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *FindRouteRequest) Reset() {
	*x = FindRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_route_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRouteRequest) ProtoMessage() {}

func (x *FindRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_route_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRouteRequest.ProtoReflect.Descriptor instead.
func (*FindRouteRequest) Descriptor() ([]byte, []int) {
	return file_services_route_route_proto_rawDescGZIP(), []int{0}
}

func (x *FindRouteRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *FindRouteRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type FindRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EtaSeconds int32 `protobuf:"varint,1,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
}

func (x *FindRouteResponse) Reset() {
	*x = FindRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_route_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRouteResponse) ProtoMessage() {}

func (x *FindRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_route_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRouteResponse.ProtoReflect.Descriptor instead.
func (*FindRouteResponse) Descriptor() ([]byte, []int) {
	return file_services_route_route_proto_rawDescGZIP(), []int{1}
}

func (x *FindRouteResponse) GetEtaSeconds() int32 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

var File_services_route_route_proto protoreflect.FileDescriptor

var file_services_route_route_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x11, 0x46,
	0x69, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x74, 0x61, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x32, 0x4f, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f, 0x74, 0x2f, 0x68, 0x6f, 0x74, 0x72, 0x6f, 0x64,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_route_route_proto_rawDescOnce sync.Once
	file_services_route_route_proto_rawDescData = file_services_route_route_proto_rawDesc
)

func file_services_route_route_proto_rawDescGZIP() []byte {
	file_services_route_route_proto_rawDescOnce.Do(func() {
		file_services_route_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_route_route_proto_rawDescData)
	})
	return file_services_route_route_proto_rawDescData
}

var file_services_route_route_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_route_route_proto_goTypes = []interface{}{
	(*FindRouteRequest)(nil),  // 0: route.FindRouteRequest
	(*FindRouteResponse)(nil), // 1: route.FindRouteResponse
}
var file_services_route_route_proto_depIdxs = []int32{
	0, // 0: route.RoutesService.FindRoute:input_type -> route.FindRouteRequest
	1, // 1: route.RoutesService.FindRoute:output_type -> route.FindRouteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_route_route_proto_init() }
func file_services_route_route_proto_init() {
	if File_services_route_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_route_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_route_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_route_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_route_route_proto_goTypes,
		DependencyIndexes: file_services_route_route_proto_depIdxs,
		MessageInfos:      file_services_route_route_proto_msgTypes,
	}.Build()
	File_services_route_route_proto = out.File
	file_services_route_route_proto_rawDesc = nil
	file_services_route_route_proto_goTypes = nil
	file_services_route_route_proto_depIdxs = nil
}
