apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: hotrod
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
spec:
  template:
    spec:
      containers:
      - name: hotrod
        imagePullPolicy: Never