apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hotrod
    component: driver
  name: driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
      component: driver
  template:
    metadata:
      labels:
        app: hotrod
        component: driver
    spec:
      containers:
        - name: hotrod
          args:
            - driver
            - --verbose
          env:
            - name: BASELINE_NAME
              value: "driver"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4318"
          image: signadot/hotrod:latest
          imagePullPolicy: Always
      restartPolicy: Always
