apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hotrod
    component: route
  name: route
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
      component: route
  template:
    metadata:
      labels:
        app: hotrod
        component: route
    spec:
      containers:
        - name: hotrod
          args:
            - route
          env:
            - name: BASELINE_NAME
              value: "route"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4318"
          image: signadot/hotrod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: grpc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hotrod
    component: route
  name: route
spec:
  ports:
    - name: grpc
      port: 8083
  selector:
    app: hotrod
    component: route
