apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hotrod
    component: driver
  name: driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
      component: driver
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.signadot.com/inject: "grpc"
      labels:
        app: hotrod
        component: driver
    spec:
      containers:
        - args:
            - driver
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger
            - name: JAEGER_AGENT_PORT
              value: "6831"
          image: signadot/hotrod:latest
          imagePullPolicy: Always
          name: hotrod
          ports:
            - containerPort: 8082
              name: web
      restartPolicy: Always
      imagePullSecrets:
      - name: signadot-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hotrod
    component: driver
  name: driver
spec:
  ports:
    - name: grpc-web
      port: 8082
      targetPort: web
  selector:
    app: hotrod
    component: driver
