apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hotrod
    component: location
  name: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
      component: location
  template:
    metadata:
      labels:
        app: hotrod
        component: location
    spec:
      containers:
        - name: hotrod
          args:
            - location
          env:
            - name: SIGNADOT_BASELINE_KIND
              value: Deployment
            - name: SIGNADOT_BASELINE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SIGNADOT_BASELINE_NAME
              value: "location"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4318"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_PASS
              value: abc
          image: signadot/hotrod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http-api
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hotrod
    component: location
  name: location
spec:
  ports:
    - name: http-api
      port: 8081
  selector:
    app: hotrod
    component: location
