apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: route
spec:
  rules:
    - matches:
        - method:
            method: FindRoute
            service: route.RoutesService
            type: Exact
